name: Release (beta)

on: workflow_dispatch

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # path: slides
      - uses: goto-bus-stop/setup-zig@v1
      - uses: actions/checkout@v2
        with:
          repository: prime31/zig-upaya
          ref: 154417379bfaa36f51c3b1b438fa73cf563d90f0
          submodules: true
          path: zig-upaya
      # - run: find .
      - run: zig build -Drelease-safe
